#!/bin/bash

#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20G
#SBATCH --time=00:60:00

set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_report
mkdir -p out_figs



singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py


